# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

#### setup config #####

configfile: "config/config.yaml"

from snakemake.utils import min_version

min_version("7.14.0")


include: "rules/prep_refs.smk"



